version: '2'
services:
  sachabijoux-app:
    image: sachabijoux
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sachabijoux-postgresql:5432/sachabijoux
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  sachabijoux-postgresql:
    extends:
      file: postgresql.yml
      service: sachabijoux-postgresql
